name: Report an issue
description: Create a bug report to fix an issue
title: "Issue: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities. For security vulnerabilities, see our [security policy](https://github.com/canonical/ubuntu-insights-k8s-operator/security).

        Thanks for taking the time to report an issue and help improve the Ubuntu Insights Juju charm! Please fill out the form below as
        best as you can so that we can help you.

        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).

        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: >
        Provide a clear and concise description of what the issue is, including what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce it
      description: >
        Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced
        consistently or if it is intermittent.
      placeholder: |
        Redact any sensitive information.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        We need to know a bit more about the context in which you run the charm.
        - Are you running Juju locally, on lxd, in multipass or on some other platform?
        - What channel and revision you deployed the charm from (i.e. `latest/edge` or similar).
        - Version of any applicable components, like the juju snap, the model controller, lxd, microk8s, and/or multipass.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        Fetch the logs using `juju debug-log --replay` and `kubectl logs ...`. Additional details available in the juju docs 
        at https://documentation.ubuntu.com/juju/3.6/howto/manage-logs/#manage-logs
      render: shell
      placeholder: |
        Redact any sensitive information.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant information
      description: >
        Please include any additional relevant information that may help us investigate the issue.

  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
