name: Validate pull request title

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate:
    name: Validate PR title
    if: >-
      github.event.pull_request.head.ref != 'chore/auto-libs' ||
      github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: canonical/desktop-engineering/gh-actions/common/validate-pr-title@main
